#!/usr/bin/env bash

# Injects libraries generated by kivy's distribute.sh script into pydroid in
# general or into a specific pydroid app.

# Example usage:
# ./copy_kivy_libs.sh

DEV_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PYDROID_ROOT_DIR=$DEV_DIR/..

######################## PATHS TO ADAPT #######################################

PYTHON_FOR_ANDROID_DIR=$HOME/python-for-android

# Uncomment this, if you want to inject the libs into pydroid in general
APP_DIR=$PYDROID_ROOT_DIR/src/pydroid/framework/project_skeleton

# Uncomment and adapt this, if you want to inject the libs only into a specific app
# APP_DIR=$HOME/pydroid_test/pyjnius_example

######################## NO MORE ADAPTIONS REQUIRED ###########################


SRC_DIR=$PYTHON_FOR_ANDROID_DIR/dist/default
SRC_LIBS_DIR=$SRC_DIR/libs/armeabi
SRC_PYTHON_INSTALL_DIR=$SRC_DIR/python-install
SRC_DEPENDENCIES_DIR=$SRC_PYTHON_INSTALL_DIR/include/python2.7
SRC_PYTHON_2_7_DIR=$SRC_PYTHON_INSTALL_DIR/lib/python2.7


DST_LIBS_DIR=$APP_DIR/libs
DST_PYTHON27_DIR=$DST_LIBS_DIR/python27
DST_DEPENDENCIES_DIR=$DST_PYTHON27_DIR/build_dependencies
DST_PYTHON_2_7_DIR=$DST_PYTHON27_DIR/lib/python2.7
BACKUP_DIR=$DST_LIBS_DIR/backup
PYSIDE_DIR=$DST_PYTHON_2_7_DIR/site-packages/PySide

# Move libshiboken, libpyside and PySide to a save place
mkdir -p $BACKUP_DIR
mv $DST_PYTHON27_DIR/libpyside.so $BACKUP_DIR/libpyside.so
mv $DST_PYTHON27_DIR/libshiboken.so $BACKUP_DIR/libshiboken.so
mv $PYSIDE_DIR $BACKUP_DIR


# Remove old libraries
rm -f $DST_PYTHON27_DIR/*.so
rm -rf $DST_DEPENDENCIES_DIR
rm -rf $DST_PYTHON_2_7_DIR

# Copy new files
cp -r $SRC_DEPENDENCIES_DIR $DST_DEPENDENCIES_DIR
cp -r $SRC_PYTHON_2_7_DIR $DST_PYTHON_2_7_DIR
cp $SRC_LIBS_DIR/*.so $DST_PYTHON27_DIR
cp $SRC_DIR/private/libpymodules.so $DST_PYTHON27_DIR

# Restore libshiboken and libpyside
mv $BACKUP_DIR/libpyside.so $DST_PYTHON27_DIR/libpyside.so
mv $BACKUP_DIR/libshiboken.so $DST_PYTHON27_DIR/libshiboken.so
mv $BACKUP_DIR/PySide $PYSIDE_DIR

# Remove the backup directory
rm -rf $BACKUP_DIR

echo Done.
