#!/bin/bash

# renames the application
# -> just replace NEW_NAME and NEW_UNIQU_NAME with with valid names of you choice and you are set :)
#
# NOTE: value NEW_UNIQUE_NAME should be unique as not to clash with other
# unique Android application names

if [ $# -ne 2 ]
then
    echo "Invalid Argument Count!"
    echo "Syntax: $0 new_name domain"
    exit
fi

NEW_NAME=$1
NEW_UNIQUE_NAME=$2.$1

mv ProjectSkeleton.pro "${NEW_NAME}.pro"
sed -i "s/ProjectSkeleton/${NEW_NAME}/g" "${NEW_NAME}.pro"
sed -i "s/org.modrana.ProjectSkeleton/${NEW_UNIQUE_NAME}/g" main.h
sed -i "s/org.modrana.ProjectSkeleton/${NEW_UNIQUE_NAME}/g" android/src/org/kde/necessitas/origo/QtActivity.java
sed -i "s/org.modrana.ProjectSkeleton/${NEW_UNIQUE_NAME}/g" android/AndroidManifest.xml
sed -i "s/ProjectSkeleton/${NEW_NAME}/g" android/AndroidManifest.xml
sed -i "s/ProjectSkeleton/${NEW_NAME}/g" android/res/values/strings.xml
sed -i "s/ProjectSkeleton/${NEW_NAME}/g" android/build.xml
